### ISSUE TITLE
"undefined reference to 'xxxx'"

### ISSUE THREAD

**Issue by pharrisee** [technicalviking/tulipindicators#3]
Hi,

I'm getting lots of "undefined reference to 'xxxx'" when 'go get'ting this library with 'go get github.com/technicalviking/tulipindicators', e.g.:

/tmp/go-build665381683/b001/_x005.o: In function `ti_acos':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/acos.c:28: undefined reference to `acos'
/tmp/go-build665381683/b001/_x015.o: In function `ti_asin':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/asin.c:28: undefined reference to `asin'
/tmp/go-build665381683/b001/_x016.o: In function `ti_atan':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/atan.c:28: undefined reference to `atan'
/tmp/go-build665381683/b001/_x019.o: In function `ti_bbands':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/bbands.c:72: undefined reference to `sqrt'
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/bbands.c:56: undefined reference to `sqrt'
/tmp/go-build665381683/b001/_x025.o: In function `ti_cos':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/cos.c:28: undefined reference to `cos'
/tmp/go-build665381683/b001/_x026.o: In function `ti_cosh':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/cosh.c:28: undefined reference to `cosh'
/tmp/go-build665381683/b001/_x040.o: In function `ti_exp':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/exp.c:28: undefined reference to `exp'

_more snipped out here_

/tmp/go-build808234139/b001/_x085.o: In function `ti_tan':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/tan.c:28: undefined reference to `tan'
/tmp/go-build808234139/b001/_x086.o: In function `ti_tanh':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/tanh.c:28: undefined reference to `tanh'
/tmp/go-build808234139/b001/_x099.o: In function `ti_vidya':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/vidya.c:96: undefined reference to `sqrt'
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/vidya.c:95: undefined reference to `sqrt'
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/vidya.c:72: undefined reference to `sqrt'
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/vidya.c:71: undefined reference to `sqrt'
/tmp/go-build808234139/b001/_x100.o: In function `ti_volatility':
/home/phil/gocode/src/github.com/technicalviking/tulipindicators/volatility.c:66: undefined reference to `sqrt'

Any ideas as to what I'm doing wrong?

This is on Ubuntu 17.10, go version is 1.10rc1 (not sure if that makes a difference)

**Comment by pharrisee** [comment]
OK, fixed it (I think), by adding this line:

#cgo LDFLAGS: -lm

to tulipindicators.go

I'll test a bit more, and possibly stick in a PR.

**Comment by Code-exE-Software** [comment]
I've gone ahead and merged your PR.  Thank you very much!   
The plugin was developed using go 1.9.2 on Windows 10, so my version may have just included the required system headers, since math.h is referenced in tulipindicators.h.
